# IoT Bees Yocto layer
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-iotbees"
BBFILE_PATTERN_meta-iotbees = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-iotbees = "10"

LAYERDEPENDS_meta-iotbees = "core"
LAYERSERIES_COMPAT_meta-iotbees = "scarthgap"
