# IoT Bees distro definition
require conf/distro/poky.conf

DISTRO = "iotbees"
DISTRO_NAME = "IoT Bees"
DISTRO_VERSION = "0.1.0"
MAINTAINER = "IoT Bees <prasanth.iot@gmail.com>"

DISTRO_FEATURES:append = " systemd bluetooth wifi usrmerge"
VIRTUAL-RUNTIME_init_manager = "systemd"

COPY_LIC_MANIFEST = "1"
COPY_LIC_DIRS = "1"
